name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        uses: huggingface/spaces-github-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          hf_token: ${{ secrets.HF_TOKEN }}
          space_id: adityaulil/DermaScan_AI
